import { Wand, Alignment } from '../types'
import { getWandSvg } from './wandImages'

export const wands: Wand[] = [
  // ── GOOD ALIGNMENT ──────────────────────────────────────────────
  {
    id: 'good-001',
    name: "Wand of Holy Light",
    alignment: 'Good',
    description: "Carved from sacred ivory and tipped with a fragment of captured sunrise, this wand blazes with an inner warmth that drives away darkness. Paladins and clerics of the light revere it as a holy relic.",
    price: 1200,
    rarity: 'Very Rare',
    magicalProperties: [
      'Emits a 30-ft aura of bright holy light on command',
      'Deals radiant damage to undead and fiends',
      'Grants advantage on saving throws against fear',
    ],
    specialEffect: "Smite of the Eternal Dawn — blinds all undead within 60 ft for 1 minute",
    imageUrl: getWandSvg('good-001'),
  },
  {
    id: 'good-002',
    name: "Celestial Shepherd's Staff",
    alignment: 'Good',
    description: "Fashioned from a branch of the World Tree, this staff hums with the gentle power of celestial patronage. Those who carry it feel a faint warmth on their shoulders, as if watched over by benevolent eyes.",
    price: 2200,
    rarity: 'Legendary',
    magicalProperties: [
      'Casts Mass Cure Wounds once per dawn',
      'Summons a Celestial Pegasus as a mount for 8 hours',
      'Protects all allies within 20 ft from charm effects',
      'Glows gold when evil creatures are within 120 ft',
    ],
    specialEffect: "Shepherd's Blessing — restores all hit points to one willing creature",
    imageUrl: getWandSvg('good-002'),
  },
  {
    id: 'good-003',
    name: "Dawn's First Blessing",
    alignment: 'Good',
    description: "This slender wand of polished ash is infused with the magic of sunrise prayers. It was crafted by dawn-priests who rose every morning for seven years to enchant it with first light.",
    price: 320,
    rarity: 'Uncommon',
    magicalProperties: [
      'Casts Bless on up to three creatures',
      'Sheds soft golden light in a 10-ft radius',
    ],
    specialEffect: "Morning Renewal — removes one level of exhaustion from a touched creature",
    imageUrl: getWandSvg('good-003'),
  },
  {
    id: 'good-004',
    name: "Guardian's Silver Wand",
    alignment: 'Good',
    description: "Wrapped in bands of celestial silver and etched with angelic script, this wand is a ward against all evil. Soldiers of righteousness carry it into battle as both weapon and talisman.",
    price: 650,
    rarity: 'Rare',
    magicalProperties: [
      'Casts Protection from Evil and Good at will',
      'Silver tip deals extra damage to lycanthropes and vampires',
      'Immune to magical disarming effects',
    ],
    specialEffect: "Silver Aegis — creates a shimmering barrier absorbing the next 30 damage",
    imageUrl: getWandSvg('good-004'),
  },
  {
    id: 'good-005',
    name: "Verdant Nature's Wand",
    alignment: 'Good',
    description: "Grown rather than carved, this living twig from an elder dryad's grove sprouts fresh leaves in spring. It channels the raw, nurturing power of the natural world.",
    price: 80,
    rarity: 'Common',
    magicalProperties: [
      'Accelerates plant growth within 10 ft',
      'Casts Speak with Plants once per day',
    ],
    specialEffect: "Thornwall — causes a dense briar wall 10 ft long to spring from the earth",
    imageUrl: getWandSvg('good-005'),
  },
  {
    id: 'good-006',
    name: "Healer's Gentle Rod",
    alignment: 'Good',
    description: "Smooth white bone and wrapped in soft linen, this rod radiates an unmistakeable warmth of healing energy. Field medics and battlefield clerics prize it above all other tools.",
    price: 480,
    rarity: 'Rare',
    magicalProperties: [
      'Casts Cure Wounds at 3rd level without expending a spell slot (3/day)',
      'Stabilises dying creatures automatically on touch',
      'Grants resistance to necrotic damage to the wielder',
    ],
    specialEffect: "Mending Touch — removes one disease or condition from a touched creature",
    imageUrl: getWandSvg('good-006'),
  },
  {
    id: 'good-007',
    name: "Sunfire Conduit",
    alignment: 'Good',
    description: "Forged at the heart of a solar eclipse by a guild of sun-mages, this wand captures the furious radiance of the sun. It scorches the wicked while warming the virtuous.",
    price: 900,
    rarity: 'Very Rare',
    magicalProperties: [
      'Casts Sunburst once per long rest',
      'Deals radiant damage on every melee strike',
      'Dispels magical darkness within 60 ft',
    ],
    specialEffect: "Corona Blast — releases a 20-ft burst of blinding sunfire",
    imageUrl: getWandSvg('good-007'),
  },
  {
    id: 'good-008',
    name: "Wand of Pure Waters",
    alignment: 'Good',
    description: "Carved from driftwood blessed by a sea-priest of the Good Tides, this wand calls upon the cleansing power of sacred water. It purifies corruption wherever it flows.",
    price: 130,
    rarity: 'Common',
    magicalProperties: [
      'Purifies up to 10 gallons of contaminated water per casting',
      'Casts Create Water at will',
    ],
    specialEffect: "Holy Torrent — releases a wave of blessed water that repels undead 30 ft",
    imageUrl: getWandSvg('good-008'),
  },
  {
    id: 'good-009',
    name: "Starlight Warden's Wand",
    alignment: 'Good',
    description: "This midnight-blue wand is set with chips of genuine meteorite that twinkle like distant stars. Rangers who patrol the wilderness at night carry it as a guiding beacon.",
    price: 360,
    rarity: 'Uncommon',
    magicalProperties: [
      'Casts Starfall (magical star-shaped bolts) at range',
      'Illuminates invisible creatures within 30 ft',
      'Grants darkvision 60 ft for 8 hours',
    ],
    specialEffect: "Constellation Mark — marks a target; all allies gain advantage on attacks against it",
    imageUrl: getWandSvg('good-009'),
  },
  {
    id: 'good-010',
    name: "Paladin's Oath Sceptre",
    alignment: 'Good',
    description: "A heavy sceptre of white oak banded with consecrated gold, this weapon is bonded to its wielder on first use in a solemn magical oath. Only the pure of heart can lift it.",
    price: 1800,
    rarity: 'Legendary',
    magicalProperties: [
      'Doubles the wielder\'s Divine Smite damage',
      'Casts Aura of Virtue, granting allies +3 to saving throws',
      'Cannot be attuned by chaotic or evil creatures',
      'Returns to the wielder\'s hand if thrown',
    ],
    specialEffect: "Sacred Vow — compels a fiend or undead to make a Wisdom save or be banished",
    imageUrl: getWandSvg('good-010'),
  },
  {
    id: 'good-011',
    name: "Wand of Whispering Wind",
    alignment: 'Good',
    description: "Light as a feather and carved from the highest branch of a cloud-oak, this wand channels the breath of mountain zephyrs. Scouts and messengers carry it to keep allies informed across vast distances.",
    price: 200,
    rarity: 'Uncommon',
    magicalProperties: [
      'Sends messages up to one mile as carried whispers',
      'Casts Gust of Wind to disperse gases and smoke',
    ],
    specialEffect: "Gale Step — grants the wielder Fly speed 40 ft for one round",
    imageUrl: getWandSvg('good-011'),
  },
  {
    id: 'good-012',
    name: "Compassion's Lantern Wand",
    alignment: 'Good',
    description: "This wand is topped with a tiny glass bead that holds an everlasting mote of warm light. It was made by a monk who spent forty years tending the sick and dying.",
    price: 560,
    rarity: 'Rare',
    magicalProperties: [
      'Creates a beacon visible to allies within one mile',
      'Casts Sanctuary on self or an ally (5/day)',
      'Creatures within 10 ft gain +1d4 to death saving throws',
    ],
    specialEffect: "Beacon of Hope — all allies within 30 ft regain maximum hit points on their next healing",
    imageUrl: getWandSvg('good-012'),
  },

  // ── NEUTRAL ALIGNMENT ───────────────────────────────────────────
  {
    id: 'neut-001',
    name: "Wand of Arcane Balance",
    alignment: 'Neutral',
    description: "Forged from the union of two opposing essences — fire and ice — this wand embodies perfect equilibrium. It amplifies neither beneficence nor malice, only the raw power of measured magic.",
    price: 700,
    rarity: 'Rare',
    magicalProperties: [
      'Absorbs one spell of 4th level or lower per day',
      'Releases absorbed spell energy as a counterspell',
      'Caster level scales with the number of schools mastered',
    ],
    specialEffect: "Nullfield — creates a 15-ft antimagic bubble lasting 1 round",
    imageUrl: getWandSvg('neut-001'),
  },
  {
    id: 'neut-002',
    name: "Chronicler's Quill-Wand",
    alignment: 'Neutral',
    description: "This elegant ivory wand doubles as a quill pen of extraordinary precision. It was crafted by scholars of the Unseen Library to record events as they occur, transcribing reality into permanent ink.",
    price: 250,
    rarity: 'Uncommon',
    magicalProperties: [
      'Scribes spells into prepared scrolls at half the normal time',
      'Casts Comprehend Languages at will',
    ],
    specialEffect: "True Record — instantly copies any written text within 30 ft onto a blank sheet",
    imageUrl: getWandSvg('neut-002'),
  },
  {
    id: 'neut-003',
    name: "Tide Turner's Rod",
    alignment: 'Neutral',
    description: "Carved from narwhal bone and engraved with tidal charts, this rod embodies the patient power of the sea. It does not serve good or evil — it serves the relentless will of the waves.",
    price: 420,
    rarity: 'Rare',
    magicalProperties: [
      'Casts Control Water within a 300-ft cube',
      'Summons a Water Elemental once per tide (12 hours)',
      'Grants the wielder water breathing',
    ],
    specialEffect: "Undertow — pulls all creatures in a 20-ft line 30 ft toward the caster",
    imageUrl: getWandSvg('neut-003'),
  },
  {
    id: 'neut-004',
    name: "Hourglass of Moments Wand",
    alignment: 'Neutral',
    description: "A hollow glass wand containing fine silver sand that falls perpetually upward. Made by chronomancers, it bends the flow of time for brief but decisive instants.",
    price: 1350,
    rarity: 'Very Rare',
    magicalProperties: [
      'Casts Haste on self (3/day)',
      'Casts Slow on a target (3/day)',
      'Allows a re-roll of any one die once per long rest',
    ],
    specialEffect: "Temporal Stasis — freezes one creature in time for 1 round (no save, no action)",
    imageUrl: getWandSvg('neut-004'),
  },
  {
    id: 'neut-005',
    name: "Wand of Stone Silence",
    alignment: 'Neutral',
    description: "Hewn from a single piece of deep granite and polished smooth by mountain rivers, this wand carries the stoic patience of the earth itself. It does not judge; it simply endures.",
    price: 100,
    rarity: 'Common',
    magicalProperties: [
      'Casts Silence in a 15-ft radius',
      'Grants resistance to thunder damage',
    ],
    specialEffect: "Earthen Anchor — prevents a creature from being moved or teleported for 1 round",
    imageUrl: getWandSvg('neut-005'),
  },
  {
    id: 'neut-006',
    name: "Mirror of Truths Wand",
    alignment: 'Neutral',
    description: "The tip of this silver wand is set with a polished obsidian mirror-gem. It reflects not light but intention, revealing the true nature of magic and illusions without bias or favour.",
    price: 380,
    rarity: 'Uncommon',
    magicalProperties: [
      'Sees through illusions automatically within 30 ft',
      'Casts True Seeing for 1 minute (1/day)',
    ],
    specialEffect: "Mirror Reversal — reflects one targeted spell back at its caster",
    imageUrl: getWandSvg('neut-006'),
  },
  {
    id: 'neut-007',
    name: "Wanderer's Path Rod",
    alignment: 'Neutral',
    description: "Constructed from a dozen different woods from a dozen different forests, this rod has travelled further than its wielders. It points the way when all paths seem closed.",
    price: 60,
    rarity: 'Common',
    magicalProperties: [
      'Casts Find the Path once per day',
      'Grants advantage on Survival checks in wilderness',
    ],
    specialEffect: "Pathfinder's Stride — doubles movement speed for 1 minute",
    imageUrl: getWandSvg('neut-007'),
  },
  {
    id: 'neut-008',
    name: "Dreamweaver's Wand",
    alignment: 'Neutral',
    description: "Wrapped in silken thread unspooled from a phase spider, this wand dips in and out of the boundary between waking and dream. It neither blesses nor curses — it simply shifts reality.",
    price: 850,
    rarity: 'Very Rare',
    magicalProperties: [
      'Casts Dream once per long rest, reaching any sleeping creature',
      'Casts Sleep at 5th level (no racial immunity)',
      'Caster gains advantage on Charisma checks against sleeping targets',
    ],
    specialEffect: "Lucid Prison — traps a target in a lucid nightmare for 1 minute, effectively incapacitating them",
    imageUrl: getWandSvg('neut-008'),
  },
  {
    id: 'neut-009',
    name: "Alchemist's Catalyst Wand",
    alignment: 'Neutral',
    description: "Brass-capped and smelling faintly of sulphur and sage, this wand was designed for the alchemical arts. It accelerates reactions without caring whether the result is cure or poison.",
    price: 175,
    rarity: 'Uncommon',
    magicalProperties: [
      'Doubles the potency of any alchemical mixture within 5 ft',
      'Casts Transmute Rock at reduced cost',
    ],
    specialEffect: "Grand Transmutation — converts any single non-magical object into another of equal mass",
    imageUrl: getWandSvg('neut-009'),
  },
  {
    id: 'neut-010',
    name: "Stormcaller's Balance Wand",
    alignment: 'Neutral',
    description: "Dark walnut streaked with veins of amber that crackle with static, this wand summons the indifferent fury of storms. Lightning obeys no alignment — only physics.",
    price: 600,
    rarity: 'Rare',
    magicalProperties: [
      'Casts Call Lightning (3/day)',
      'Grants immunity to lightning and thunder damage',
      'Disables metal-armoured targets with electromagnetic pulses',
    ],
    specialEffect: "Tempest Crown — summons a personal storm that deals 2d10 lightning to all adjacent attackers",
    imageUrl: getWandSvg('neut-010'),
  },
  {
    id: 'neut-011',
    name: "Wand of Shifting Forms",
    alignment: 'Neutral',
    description: "Carved from the shed antler of a great stag that could change its form at will, this wand is a masterpiece of transmutation. Form is merely a suggestion to those who wield it.",
    price: 1100,
    rarity: 'Very Rare',
    magicalProperties: [
      'Casts Polymorph at 5th level (2/day)',
      'Transforms into a simple tool or weapon on command',
      'Resists being identified by magical means',
    ],
    specialEffect: "Wild Flux — randomly transforms the target into a harmless beast for 1 minute",
    imageUrl: getWandSvg('neut-011'),
  },
  {
    id: 'neut-012',
    name: "Grey Council Arbiter's Wand",
    alignment: 'Neutral',
    description: "Plain grey ash, unadorned and efficient, this wand was issued to arbiters of the Grey Council to enforce truces and oaths. It has no opinion on justice — only on order.",
    price: 290,
    rarity: 'Uncommon',
    magicalProperties: [
      'Casts Zone of Truth (no concentration required)',
      'Detects lies spoken within 30 ft',
    ],
    specialEffect: "Council Ruling — magically compels both parties in a dispute to keep their stated word for 24 hours",
    imageUrl: getWandSvg('neut-012'),
  },

  // ── EVIL ALIGNMENT ──────────────────────────────────────────────
  {
    id: 'evil-001',
    name: "Wand of Soul Rending",
    alignment: 'Evil',
    description: "This obsidian wand screams faintly when it leaves its case, as if the souls trapped inside protest their imprisonment. Necromancers of the blackest order covet it above all else.",
    price: 2500,
    rarity: 'Legendary',
    magicalProperties: [
      'Deals necrotic damage that cannot be healed by magical means for 24 hours',
      'Steals 1d6 hit points from the target and adds them to the wielder',
      'Traps slain creature\'s soul, preventing resurrection',
      'Grants the wielder resistance to all damage while a soul is held',
    ],
    specialEffect: "Soulrend — extracts a creature's soul and imprisons it in the wand as a screaming gem",
    imageUrl: getWandSvg('evil-001'),
  },
  {
    id: 'evil-002',
    name: "Shadowweave Sceptre",
    alignment: 'Evil',
    description: "Woven from threads of solidified shadow harvested at the dead of night, this sceptre bends darkness to its will. Assassins and shadow-sorcerers prize it for the cloak of invisibility it lends.",
    price: 950,
    rarity: 'Very Rare',
    magicalProperties: [
      'Grants Greater Invisibility at will (self only)',
      'Teleports through shadows up to 60 ft',
      'Creatures struck cannot benefit from darkvision for 1 hour',
    ],
    specialEffect: "Shadow Surge — wraps target in impenetrable shadow, blinding and deafening them for 1 round",
    imageUrl: getWandSvg('evil-002'),
  },
  {
    id: 'evil-003',
    name: "Bone Collector's Staff",
    alignment: 'Evil',
    description: "Assembled from the shin-bones of seventeen fallen heroes, this grisly staff rattles with hollow malice. Its creator considered it a trophy; its wielders consider it a weapon.",
    price: 750,
    rarity: 'Rare',
    magicalProperties: [
      'Animates up to 6 skeletons from nearby bones once per day',
      'Casts Animate Dead at 5th level',
      'Skeletal minions gain +2 to attack and damage rolls',
    ],
    specialEffect: "Bone Volley — fires a spray of bone shards in a 15-ft cone dealing 6d6 piercing damage",
    imageUrl: getWandSvg('evil-003'),
  },
  {
    id: 'evil-004',
    name: "Venom Fang Wand",
    alignment: 'Evil',
    description: "Carved from the hollow fang of a great serpent demon and still seeping ichor, this wand drips poison from its tip. Assassins and poisoners keep it close — and most others keep their distance.",
    price: 340,
    rarity: 'Uncommon',
    magicalProperties: [
      'Poisons struck targets (Constitution save or poisoned for 1 hour)',
      'Injects magical venom that bypasses poison immunity',
    ],
    specialEffect: "Serpent's Embrace — wraps target in spectral serpents that paralyse them for 1 round",
    imageUrl: getWandSvg('evil-004'),
  },
  {
    id: 'evil-005',
    name: "Plague Bearer's Rod",
    alignment: 'Evil',
    description: "Covered in rotten wrappings once belonging to a plague victim, this rod hums with infectious energies. Wherever it points, disease follows. Its wielders wear gloves — always.",
    price: 520,
    rarity: 'Rare',
    magicalProperties: [
      'Spreads a custom magical disease on touch (incubation 1d4 days)',
      'Casts Contagion at 5th level (1/day)',
      'Diseased creatures in 30 ft are visible as auras to the wielder',
    ],
    specialEffect: "Pandemic — spreads the active disease to all creatures within 20 ft simultaneously",
    imageUrl: getWandSvg('evil-005'),
  },
  {
    id: 'evil-006',
    name: "Wand of Wretched Binding",
    alignment: 'Evil',
    description: "Barbed wire twisted into wand-shape and tempered with infernal flame, this wand binds its targets in chains of pure malice. Even the greatest warriors have been felled motionless by its touch.",
    price: 140,
    rarity: 'Common',
    magicalProperties: [
      'Casts Hold Person at 2nd level',
      'Bound creatures take 1d4 psychic damage per round',
    ],
    specialEffect: "Iron Will — renders a creature unable to use reaction abilities for 1 minute",
    imageUrl: getWandSvg('evil-006'),
  },
  {
    id: 'evil-007',
    name: "Tyrant's Commanding Rod",
    alignment: 'Evil',
    description: "Gilded with the gold of sacked kingdoms and topped with a screaming skull, this rod projects an aura of brutal authority. Those who gaze upon it feel an urge to kneel.",
    price: 1650,
    rarity: 'Legendary',
    magicalProperties: [
      'Casts Dominate Person at will (with save)',
      'Casts Dominate Monster once per week',
      'Creatures under domination cannot break it due to taking damage',
      'Grants the wielder Truesight while concentrating on a dominated creature',
    ],
    specialEffect: "Absolute Command — forces up to 10 humanoids to obey one short spoken instruction",
    imageUrl: getWandSvg('evil-007'),
  },
  {
    id: 'evil-008',
    name: "Dread Spectre Wand",
    alignment: 'Evil',
    description: "Cold to the touch and faintly translucent, this wand was fashioned from ectoplasm harvested from a banshee's grave. It smells of old tombs and forgotten sorrow.",
    price: 280,
    rarity: 'Uncommon',
    magicalProperties: [
      'Summons a Specter to serve for 1 hour (once per day)',
      'Casts Phantasmal Killer at 4th level',
    ],
    specialEffect: "Death Wail — emits a banshee screech forcing all within 30 ft to save or drop to 0 HP",
    imageUrl: getWandSvg('evil-008'),
  },
  {
    id: 'evil-009',
    name: "Corruptor's Touch Wand",
    alignment: 'Evil',
    description: "This black-wood wand is slick with an oily darkness that stains whatever it touches. It was made to unmake things — loyalty, sanity, and the bonds between allies.",
    price: 470,
    rarity: 'Rare',
    magicalProperties: [
      'Casts Bestow Curse at 5th level without concentration',
      'Permanently corrupts one non-magical object into a cursed item',
      'Grants the wielder immunity to the Charmed condition',
    ],
    specialEffect: "Deep Corruption — implants a compulsion in the target that surfaces at the worst possible moment",
    imageUrl: getWandSvg('evil-009'),
  },
  {
    id: 'evil-010',
    name: "Inferno Shard Wand",
    alignment: 'Evil',
    description: "A splinter of obsidian from a volcanic rift in the Nine Hells, this wand channels hellfire that burns hotter than any natural flame. It shows no mercy, and its wielder usually doesn't either.",
    price: 1000,
    rarity: 'Very Rare',
    magicalProperties: [
      'Casts Hellfire Bolt dealing fire and necrotic damage',
      'Fire damage ignores resistance (not immunity)',
      'Leaves burning curse: target takes 1d6 fire damage each turn for 1 minute',
    ],
    specialEffect: "Infernal Eruption — summons a column of hellfire 10 ft wide and 40 ft tall dealing 10d10 damage",
    imageUrl: getWandSvg('evil-010'),
  },
  {
    id: 'evil-011',
    name: "Wand of Creeping Dread",
    alignment: 'Evil',
    description: "Fashioned from the petrified finger of a lich, this slender wand exudes a psychological miasma of pure terror. Even brave warriors find their resolve crumbling in its presence.",
    price: 125,
    rarity: 'Common',
    magicalProperties: [
      'Casts Cause Fear on a single target',
      'Frightened creatures cannot move toward the wielder',
    ],
    specialEffect: "Dread Aura — fills a 30-ft sphere with supernatural fear; all creatures must save or be frightened",
    imageUrl: getWandSvg('evil-011'),
  },
  {
    id: 'evil-012',
    name: "Void Hunger Wand",
    alignment: 'Evil',
    description: "Black as a starless sky and cold as the void between worlds, this wand channels the hunger of nothingness. It does not destroy things — it unmakes them, leaving not even ash.",
    price: 1900,
    rarity: 'Legendary',
    magicalProperties: [
      'Casts Disintegrate at 6th level (2/day)',
      'Destroyed creatures cannot be resurrected by any means short of a Wish',
      'Absorbs magical auras in a 10-ft radius, dispelling active spells',
      'Wielder gains temporary HP equal to damage dealt',
    ],
    specialEffect: "Entropic Maw — opens a rift to the void that pulls all creatures within 30 ft 15 ft closer",
    imageUrl: getWandSvg('evil-012'),
  },
]

export function getWandById(id: string): Wand | undefined {
  return wands.find(w => w.id === id)
}

export function getWandsByAlignment(alignment: Alignment): Wand[] {
  return wands.filter(w => w.alignment === alignment)
}
